const db_m = {
  
    "0":{name:'Zero'},
    "1": { name: 'one' },
     "2": { name: 'two'},
     "3": {name:'three'},
     "4":{name:'four'},
    "5":{name:'five'},
    "6":{name:'six'},
    "7":{name:'seven'},
    "8":{name:'eight'},
    "9":{name:'nine'},
    "10":{name:'ten'},
    "11":{name:'eleven'},
    "12":{name:'twelve'},
    "13":{name:'thirteen'},
    "14":{name:'fourteen'},
    "15":{name:'fifteen'},
    "16":{name:'sixteen'},
    "17":{name:'seventeen'},
    "18":{name:'eighteen'},
    "19":{name:'nineteen'},
    "20":{name:'twenty'},
    "21":{name:'twenty one'},
    "22":{name:'twenty two'},
    "23":{name:'twenty three'},
    "24":{name:'twenty four'},
    "25":{name:'twenty five'},
    "26":{name:'twenty six'},
    "27":{name:'twenty seven'},
    "28":{name:'twenty eight'},
    "29":{name:'twenty nine'},
    "30":{name:'twenty nine'},
    "31":{name:'twenty nine'},
    "32":{name:'twenty nine'},
    "33":{name:'twenty nine'},
    "34":{name:'twenty nine'},
    "35":{name:'twenty nine'},
    "36":{name:'twenty nine'},
    "37":{name:'twenty nine'},
    "38":{name:'twenty nine'},
    "39":{name:'twenty nine'},
    "40":{name:'twenty nine'},
    "41":{name:'twenty nine'},
    "42":{name:'twenty nine'},
    "43":{name:'twenty nine'},
    "44":{name:'twenty nine'},
    "45":{name:'twenty nine'},
    "46":{name:'twenty nine'},
    "47":{name:'twenty nine'},
    "48":{name:'twenty nine'},
    "49":{name:'twenty nine'},
    "50":{name:'twenty nine'},
    "51":{name:'twenty nine'},
    "52":{name:'twenty nine'},
    "53":{name:'twenty nine'},
    "54":{name:'twenty nine'},
    "55":{name:'twenty nine'},
    "56":{name:'twenty nine'},
    "57":{name:'twenty nine'},
    "58":{name:'twenty nine'},
    "59":{name:'twenty nine'},
    "60":{name:'twenty nine'},
    "61":{name:'twenty nine'},
    "62":{name:'twenty nine'},
    "63":{name:'twenty nine'},
    "64":{name:'twenty nine'},
    "65":{name:'twenty nine'},
    "66":{name:'twenty nine'},
    "67":{name:'twenty nine'},
    "68":{name:'twenty nine'},
    "69":{name:'twenty nine'},
    "70":{name:'twenty nine'},
    "71":{name:'twenty nine'},
    "72":{name:'twenty nine'},
    "73":{name:'twenty nine'},
    "74":{name:'twenty nine'},
    "75":{name:'twenty nine'},
    "76":{name:'twenty nine'},
    "77":{name:'twenty nine'},
    "78":{name:'twenty nine'},
    "79":{name:'twenty nine'},
    "80":{name:'twenty nine'},
    "81":{name:'twenty nine'},
    "82":{name:'twenty nine'},
    "83":{name:'twenty nine'},
    "84":{name:'twenty nine'},
    "85":{name:'twenty nine'},
    "86":{name:'twenty nine'},
    "87":{name:'twenty nine'},
    "88":{name:'twenty nine'},
   };
   export default db_m;